apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      defaultDatabase: analytics
      server: http://clickhouse:8123
      querySettings:
        format: table
